# Environments
# SKIP_IMAGE=true|false - skip building image

variables:
  - &kaniko_image "gcr.io/kaniko-project/executor:v1.22.0-debug"
  - &app_version "23.0.7"

steps:
  set-env:
    image: debian:bookworm-slim
    environment:
      APP_VERSION: *app_version
    commands:
      - .cicd/set-env.sh
  image:
    when:
      evaluate: 'SKIP_IMAGE != "true"'
    image: *kaniko_image
    commands:
      - .cicd/set-docker-auth.sh
      - .cicd/build.sh
    secrets:
      - source: fb_harbor_usr
        target: docker_usr
      - source: fb_harbor_pwd
        target: docker_pwd
