FROM quay.io/keycloak/keycloak:25.0.6

ENV KC_CACHE=local
ENV KC_DB=postgres
ENV KC_TRANSACTION_XA_ENABLED=false
ENV QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY=false
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

RUN /opt/keycloak/bin/kc.sh build
